# Generated by Django 6.0 on 2025-12-05 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('contact', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('contact', models.BigIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('is_available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Leaser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('contact', models.BigIntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('contact', models.BigIntegerField()),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcatname', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('1', 'with driver'), ('2', 'self drive')], max_length=30)),
                ('pickup_location', models.CharField(max_length=30)),
                ('booking_date', models.DateField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('booking_status', models.BooleanField()),
                ('security_deposit', models.FloatField()),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.driver')),
                ('learer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.leaser')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Assign_Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('date', models.DateField(auto_now=True)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.booking')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('payment_type', models.CharField(choices=[('1', 'CASE'), ('2', 'UPI')], max_length=30)),
                ('transaction_date', models.DateField(auto_now=True)),
                ('transaction_status', models.BooleanField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.booking')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('comment', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.driver')),
                ('leaser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.leaser')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('1', 'with driver'), ('2', 'self drive')], max_length=30)),
                ('document_number', models.IntegerField()),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('doc_file', models.ImageField(upload_to='photos/document_images')),
                ('verification_status', models.BooleanField()),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.driver')),
                ('leaser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.leaser')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.driver')),
                ('leaser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.leaser')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('vehicle_img', models.ImageField(upload_to='photos/vehicle_images')),
                ('fare', models.IntegerField()),
                ('registration_number', models.IntegerField()),
                ('available_status', models.BooleanField()),
                ('leaser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.leaser')),
                ('vcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.vehicle_category')),
                ('vsubcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.vehicle_subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.vehicle'),
        ),
        migrations.CreateModel(
            name='Vehicle_Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_image', models.ImageField(upload_to='photos/vehicle_images')),
                ('return_date', models.DateTimeField(auto_now=True)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.booking')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.driver')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.user')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.vehicle')),
            ],
        ),
    ]