# Generated by Django 6.0 on 2025-12-05 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='learer_id',
            new_name='leaser_id',
        ),
    ]
