# Generated by Django 6.0 on 2025-12-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0002_rename_learer_id_booking_leaser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_return',
            name='vehicle_condition',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assign_driver',
            name='status',
            field=models.CharField(choices=[(1, 'available'), (2, 'unavailable')], max_length=30),
        ),
        migrations.AlterField(
            model_name='documents',
            name='document_type',
            field=models.CharField(choices=[('1', 'Aadhar card'), ('2', 'Licence card'), ('3', 'RC book')], max_length=30),
        ),
        migrations.AlterField(
            model_name='vehicle_return',
            name='return_date',
            field=models.DateField(auto_now=True),
        ),
    ]
