# Generated by Django 6.0 on 2025-12-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0003_vehicle_return_vehicle_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign_driver',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('with driver', 'With driver'), ('self drive', 'Self drive')], max_length=30),
        ),
    ]
