# Generated by Django 6.0 on 2026-01-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0004_alter_assign_driver_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(max_length=30),
        ),
    ]
