# Generated by Django 6.0 on 2026-01-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0005_alter_vehicle_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='side_angle',
            field=models.ImageField(null=True, upload_to='photos/vehicle_images'),
        ),
    ]
