# Generated by Django 6.0 on 2026-01-05 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0006_vehicle_side_angle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='side_angle',
        ),
    ]
