# Generated by Django 6.0 on 2026-01-08 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0008_alter_booking_driver_id_alter_booking_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.user'),
        ),
    ]
