# Generated by Django 6.0.1 on 2026-01-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0011_alter_booking_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='available_status',
            field=models.BooleanField(default=False),
        ),
    ]
