# Generated by Django 6.0 on 2026-01-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0012_alter_vehicle_available_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='photos/user_pfp'),
        ),
    ]
