# Generated by Django 6.0 on 2026-01-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0013_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='photos/driver_pfp'),
        ),
        migrations.AddField(
            model_name='leaser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='photos/leaser_pfp'),
        ),
    ]
