# Generated by Django 6.0 on 2026-02-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0014_driver_profile_pic_leaser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='front_angle',
            field=models.ImageField(null=True, upload_to='photos/vehicle_images'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='leftside_angle',
            field=models.ImageField(null=True, upload_to='photos/vehicle_images'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rightside_angle',
            field=models.ImageField(null=True, upload_to='photos/vehicle_images'),
        ),
    ]
