# Generated by Django 6.0 on 2026-02-06 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0015_vehicle_front_angle_vehicle_leftside_angle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.user'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='available_status',
            field=models.BooleanField(),
        ),
    ]
