# Generated by Django 6.0 on 2026-02-06 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0016_alter_payment_user_id_alter_vehicle_available_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='doc_file',
            field=models.ImageField(blank=True, null=True, upload_to='photos/document_images'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='document_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='document_type',
            field=models.CharField(choices=[('1', 'Aadhar Card'), ('2', 'Driving License'), ('3', 'RC Book'), ('4', 'Insurance'), ('5', 'PUC'), ('6', 'PAN Card')], max_length=30),
        ),
        migrations.AlterField(
            model_name='documents',
            name='driver_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rideapp.driver'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='leaser_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rideapp.leaser'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rideapp.user'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='verification_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='documents',
            unique_together={('user_id', 'document_type')},
        ),
    ]
