# Generated by Django 6.0 on 2026-02-06 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0018_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_order_id',
            new_name='razorpay_payment_id',
        ),
    ]
