# Generated by Django 6.0 on 2026-02-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0019_rename_razorpay_order_id_payment_razorpay_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
