# Generated by Django 6.0 on 2026-02-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0021_alter_booking_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
