# Generated by Django 6.0 on 2026-02-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0022_alter_booking_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='security_deposit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
