# Generated by Django 6.0 on 2026-02-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0023_alter_booking_security_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='security_deposit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
