# Generated by Django 6.0 on 2026-02-06 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0024_alter_booking_security_deposit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_amount',
        ),
    ]
