# Generated by Django 6.0 on 2026-02-06 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0026_booking_total_amount_alter_booking_security_deposit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_payment_id',
            new_name='razorpay_id',
        ),
    ]
