# Generated by Django 6.0 on 2026-02-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0027_rename_razorpay_payment_id_payment_razorpay_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='razorpay_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
