# Generated by Django 6.0 on 2026-02-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0028_alter_payment_razorpay_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(max_length=30),
        ),
    ]
