# Generated by Django 6.0 on 2026-02-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0029_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documents',
            unique_together={('user_id', 'document_type')},
        ),
        migrations.AlterField(
            model_name='documents',
            name='document_type',
            field=models.CharField(choices=[('1', 'Aadhar Card'), ('2', 'Driving License'), ('3', 'RC Book'), ('4', 'Insurance'), ('5', 'PUC')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='documents',
            unique_together={('driver_id', 'document_type'), ('leaser_id', 'document_type'), ('user_id', 'document_type')},
        ),
    ]
