# Generated by Django 6.0 on 2026-02-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0030_alter_documents_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
