# Generated by Django 6.0 on 2026-02-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0031_booking_pickup_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('with_driver', 'With driver'), ('self_drive', 'Self drive')], max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
