# Generated by Django 6.0 on 2026-03-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0032_alter_booking_booking_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='seats',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
