# Generated by Django 6.0 on 2026-03-06 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0033_vehicle_fuel_type_vehicle_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_subcategory',
            name='vcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rideapp.vehicle_category'),
        ),
    ]
