# Generated by Django 6.0 on 2026-03-06 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0036_alter_vehicle_subcategory_vcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_subcategory',
            name='vcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.vehicle_category'),
        ),
    ]
