# Generated by Django 6.0 on 2026-03-11 08:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0041_alter_vehicle_subcategory_vcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='contact',
            field=models.BigIntegerField(validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='assign_driver',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='driver_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rideapp.driver'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='leaser_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rideapp.leaser'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rideapp.user'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='document_type',
            field=models.CharField(choices=[('1', 'Aadhar Card'), ('2', 'Driving License'), ('3', 'RC Book'), ('4', 'Insurance'), ('5', 'PUC'), ('6', 'PAN Card')], max_length=30),
        ),
        migrations.AlterField(
            model_name='driver',
            name='contact',
            field=models.BigIntegerField(validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='driver_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rideapp.driver'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='leaser_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rideapp.leaser'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rideapp.user'),
        ),
        migrations.AlterField(
            model_name='leaser',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18)]),
        ),
        migrations.AlterField(
            model_name='leaser',
            name='contact',
            field=models.BigIntegerField(validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='leaser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.BigIntegerField(validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='available_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fare',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
