# Generated by Django 6.0 on 2026-03-11 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0042_alter_admin_contact_alter_admin_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='contact',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='leaser',
            name='contact',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
