# Generated by Django 6.0 on 2026-03-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0043_alter_driver_contact_alter_leaser_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pickup_lat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_lng',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
