# Generated by Django 6.0 on 2026-03-18 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0044_booking_pickup_lat_booking_pickup_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='pickup_lat',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pickup_lng',
        ),
    ]
