# Generated by Django 6.0 on 2026-03-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0045_remove_booking_pickup_lat_remove_booking_pickup_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='document_type',
            field=models.CharField(choices=[('1', 'Aadhar Card'), ('2', 'Driving License'), ('3', 'PAN Card')], max_length=30),
        ),
    ]
