# Generated by Django 6.0 on 2026-03-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0046_alter_documents_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='document_type',
            field=models.CharField(choices=[('1', 'Aadhar Card'), ('2', 'Driving License'), ('3', 'RC Book'), ('4', 'Insurance'), ('5', 'PUC'), ('6', 'PAN Card')], max_length=30),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='available_status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
