# Generated by Django 6.0 on 2026-03-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0047_alter_documents_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='available_status',
            field=models.CharField(choices=[('1', 'Available'), ('2', 'Not Available'), ('3', 'On Ride')], max_length=30, null=True),
        ),
    ]
