# Generated by Django 6.0 on 2026-03-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0048_alter_vehicle_available_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='insurance',
            field=models.FileField(blank=True, null=True, upload_to='photos/vehicle_documents'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='puc',
            field=models.FileField(blank=True, null=True, upload_to='photos/vehicle_documents'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='puc_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='puc_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='puc_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='puc_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rc_book',
            field=models.FileField(blank=True, null=True, upload_to='photos/vehicle_documents'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rc_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rc_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rc_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rc_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documents',
            name='document_type',
            field=models.CharField(choices=[('1', 'Aadhar Card'), ('2', 'Driving License'), ('6', 'PAN Card')], max_length=30),
        ),
    ]
