# Generated by Django 6.0 on 2026-03-23 19:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0049_vehicle_insurance_vehicle_insurance_expiry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rideapp.booking')),
                ('leaser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.leaser')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.vehicle')),
            ],
        ),
        migrations.DeleteModel(
            name='Vehicle_Return',
        ),
    ]
