# Generated by Django 6.0 on 2026-03-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0050_vehiclereturnrequest_delete_vehicle_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclereturnrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
