# Generated by Django 6.0 on 2026-03-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0051_alter_vehiclereturnrequest_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ride_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('on_ride', 'On Ride'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
    ]
