# Generated by Django 6.0 on 2026-04-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0052_booking_ride_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ride_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('on_ride', 'On Ride'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='not_started', max_length=20),
        ),
    ]
