# Generated by Django 6.0 on 2026-04-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0053_alter_booking_ride_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='driver_fee',
            field=models.FloatField(default=0),
        ),
    ]
