# Generated by Django 6.0 on 2026-04-05 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0054_booking_driver_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='driver_fee',
            new_name='driver_fee_per_day',
        ),
    ]
