# Generated by Django 6.0 on 2026-04-05 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0055_rename_driver_fee_booking_driver_fee_per_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='driver_fee_per_day',
            new_name='total_driver_fee',
        ),
    ]
