# Generated by Django 6.0 on 2026-04-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0056_rename_driver_fee_per_day_booking_total_driver_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pickup_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclereturnrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
