# Generated by Django 6.0.1 on 2026-04-13 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0057_alter_booking_pickup_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='contact',
            field=models.BigIntegerField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
