# Generated by Django 6.0.1 on 2026-04-13 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0059_alter_admin_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='contact',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
